/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Conexiones.BDConexion;
import Controlador.SoloLetras;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static vista.empleados.DatosAdm;

/**
 *
 * @author OMAR
 */
public class adm extends javax.swing.JDialog {
static ResultSet res;
    /**
     * Creates new form NewJDialog
     */
    public adm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
           this.setLocationRelativeTo(null);
           
           this.Cambiosadm.setVisible(false);
      
      Cedulaadm.setText(empleados.Texto);
           
        Validacionadm();
    }
    public void Validacionadm() {
        String mensaje = BDConexion.bucarCedulaE(Cedulaadm.getText());
        if (mensaje.equals("La Cedula ya Existe")) {
            CodExisteadm.setText("Cedula empleado");
            ModificarAdm2.setEnabled(true);
            EspecialidadAdm2.setEnabled(true);
            if (Cedulaadm.getText().length() == 8 && !EspecialidadAdm2.getText().isEmpty()) {
            saveadm.setEnabled(true);
            }
        } else if (Cedulaadm.getText().isEmpty()) {
            CodExisteadm.setText("");

        } else {
            CodExisteadm.setText("Cedula no Registrada");
            ModificarAdm2.setEnabled(false);
            EspecialidadAdm2.setEnabled(false);
            saveadm.setEnabled(false);
        }
    }
    public void GuardarAdmin(){
         if (Cedulaadm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "rellene todos los campos obligatorios", "informacion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                String Ced, Espec;
                BDConexion.EntradaAdministrativo(
                   
                    Espec = EspecialidadAdm2.getText(),
                         Ced = Cedulaadm.getText()
                );
                EspecialidadAdm2.setText("");

                JOptionPane.showMessageDialog(null, "Guardado Exitoso");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

        }

        EspecialidadAdm2.setEnabled(false);
        Texto2 = Cedulaadm.getText();
    }
    public void GuardarCambios(){
         try {
            PreparedStatement pps = Conexiones.Conexion.getConexion().prepareStatement("update ADMINISTRATIVO set ESPECIALIDAD='"
                + EspecialidadAdm2.getText()
                + "' where CI='" + Cedulaadm.getText() + "'");
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "LOS DATOS HAN SIDO MODIFICADOS");

            EspecialidadAdm2.setText("");
            EspecialidadAdm2.requestFocus();
            DatosAdm.setEnabled(false);

        } catch (SQLException e) {
        }
        Cedulaadm.setText("");
        EspecialidadAdm2.setEnabled(false);
        this.Cambiosadm.setEnabled(false);
        saveadm.setEnabled(true);
    }
    public void ModificarAdmin(){
         if (Cedulaadm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Coloque Bien sus Datos", "Error", JOptionPane.ERROR_MESSAGE);
            Cedulaadm.setText("");
            Cedulaadm.requestFocus();
        } else {
            try {
                String b;
                BDConexion.BuscarAdm(Integer.parseInt(Cedulaadm.getText()));
                b = Cedulaadm.getText();

                Cedulaadm.requestFocus();
                EspecialidadAdm2.requestFocus();

                res = Conexiones.Conexion.Consulta("select ESPECIALIDAD,CI FROM ADMINISTRATIVO");
                while (res.next()) {
                    if (res.getString(1).equals(b)) {
                        JOptionPane.showMessageDialog(null, "Datos Encontrados");
                        Cedulaadm.setText(res.getString(1));
                        EspecialidadAdm2.setText(res.getString(2));

                    }

                }
                Cedulaadm.setEditable(false);
                DatosAdm.setEnabled(false);

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        EspecialidadAdm2.setEnabled(true);
        this.Cambiosadm.setVisible(true);
        saveadm.setVisible(false);
    }

    
    public static String Texto2 = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EspecialidadAdm2 = new javax.swing.JTextField();
        VolverEmple1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Cedulaadm = new javax.swing.JTextField();
        CodExisteadm = new javax.swing.JTextField();
        ModificarAdm2 = new javax.swing.JButton();
        Cambiosadm = new javax.swing.JButton();
        saveadm = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 206, 209));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_microsoft_admin_30px.png"))); // NOI18N
        jLabel1.setText("Administrador");

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Especialidad");

        EspecialidadAdm2.setBackground(new java.awt.Color(204, 206, 209));
        EspecialidadAdm2.setBorder(null);
        EspecialidadAdm2.setEnabled(false);
        EspecialidadAdm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspecialidadAdm2ActionPerformed(evt);
            }
        });
        EspecialidadAdm2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                EspecialidadAdm2KeyTyped(evt);
            }
        });

        VolverEmple1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_arrow_64px.png"))); // NOI18N
        VolverEmple1.setBorder(null);
        VolverEmple1.setContentAreaFilled(false);
        VolverEmple1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                VolverEmple1MouseMoved(evt);
            }
        });
        VolverEmple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverEmple1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Cédula");

        Cedulaadm.setBackground(new java.awt.Color(204, 206, 209));
        Cedulaadm.setBorder(null);
        Cedulaadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CedulaadmActionPerformed(evt);
            }
        });
        Cedulaadm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CedulaadmKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CedulaadmKeyTyped(evt);
            }
        });

        CodExisteadm.setEditable(false);
        CodExisteadm.setBackground(new java.awt.Color(204, 206, 209));
        CodExisteadm.setBorder(null);

        ModificarAdm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_property_26px.png"))); // NOI18N
        ModificarAdm2.setText("Modificar");
        ModificarAdm2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ModificarAdm2.setContentAreaFilled(false);
        ModificarAdm2.setEnabled(false);
        ModificarAdm2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ModificarAdm2MouseMoved(evt);
            }
        });
        ModificarAdm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarAdm2ActionPerformed(evt);
            }
        });
        ModificarAdm2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ModificarAdm2KeyTyped(evt);
            }
        });

        Cambiosadm.setBackground(new java.awt.Color(142, 252, 199));
        Cambiosadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_26px_1.png"))); // NOI18N
        Cambiosadm.setText("Guardar");
        Cambiosadm.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Cambiosadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiosadmActionPerformed(evt);
            }
        });
        Cambiosadm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CambiosadmKeyTyped(evt);
            }
        });

        saveadm.setBackground(new java.awt.Color(142, 252, 199));
        saveadm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_26px_1.png"))); // NOI18N
        saveadm.setText("Guardar");
        saveadm.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        saveadm.setEnabled(false);
        saveadm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveadmActionPerformed(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator8.setForeground(new java.awt.Color(0, 0, 102));

        jSeparator9.setBackground(new java.awt.Color(0, 51, 102));
        jSeparator9.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(VolverEmple1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Cedulaadm, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(CodExisteadm, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(EspecialidadAdm2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cambiosadm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(saveadm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(ModificarAdm2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(VolverEmple1)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cedulaadm, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CodExisteadm, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(EspecialidadAdm2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cambiosadm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveadm, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ModificarAdm2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EspecialidadAdm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspecialidadAdm2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspecialidadAdm2ActionPerformed

    private void EspecialidadAdm2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EspecialidadAdm2KeyTyped
        SoloLetras.letrasYespacio(evt, EspecialidadAdm2.getText());
    }//GEN-LAST:event_EspecialidadAdm2KeyTyped

    private void VolverEmple1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverEmple1MouseMoved
        
    }//GEN-LAST:event_VolverEmple1MouseMoved

    private void VolverEmple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverEmple1ActionPerformed
        dispose();
    }//GEN-LAST:event_VolverEmple1ActionPerformed

    private void CedulaadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CedulaadmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CedulaadmActionPerformed

    private void CedulaadmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaadmKeyReleased
        Validacionadm();

    }//GEN-LAST:event_CedulaadmKeyReleased

    private void CedulaadmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CedulaadmKeyTyped
        char car = evt.getKeyChar();
        if (Cedulaadm.getText().length() >= 8) {
            evt.consume();
        }
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_CedulaadmKeyTyped

    private void ModificarAdm2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarAdm2MouseMoved

    }//GEN-LAST:event_ModificarAdm2MouseMoved

    private void ModificarAdm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarAdm2ActionPerformed
       ModificarAdmin();
    }//GEN-LAST:event_ModificarAdm2ActionPerformed

    private void ModificarAdm2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ModificarAdm2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarAdm2KeyTyped

    private void CambiosadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiosadmActionPerformed
       GuardarCambios();
    }//GEN-LAST:event_CambiosadmActionPerformed

    private void CambiosadmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CambiosadmKeyTyped
        Cambiosadm.setToolTipText("Guardar Cambios");
    }//GEN-LAST:event_CambiosadmKeyTyped

    private void saveadmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveadmActionPerformed
       GuardarAdmin();
    }//GEN-LAST:event_saveadmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                adm dialog = new adm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Cambiosadm;
    public static javax.swing.JTextField Cedulaadm;
    public static javax.swing.JTextField CodExisteadm;
    public static javax.swing.JTextField EspecialidadAdm2;
    public static javax.swing.JButton ModificarAdm2;
    public static javax.swing.JButton VolverEmple1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    public static javax.swing.JButton saveadm;
    // End of variables declaration//GEN-END:variables
}
