/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
 
 

/**
 *
 * @author rosan
 */
public class EstuyRepre extends javax.swing.JDialog {
static ResultSet res;
    /**
     * Creates new form EstuyRepre
     */
    public EstuyRepre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
           this.setLocationRelativeTo(null);
            CargarDatos();
    }
    public void  CargarDatos(){
        DefaultTableModel modelo =(DefaultTableModel) Tmodulo.getModel();
        modelo.setRowCount(0);
        res = Conexiones.Conexion.Consulta(" SELECT P_NOMBRE,P_APELLIDO,PREF,NUMERO,PARENTESCO,ESTUDIANTE_PUEDE_TENER_REPRESENTANTE.CIR" +
" ,ESTUDIANTE.CI FROM PERSONA  JOIN ESTUDIANTE_PUEDE_TENER_REPRESENTANTE" +
" ON ESTUDIANTE_PUEDE_TENER_REPRESENTANTE.CIR=PERSONA.CI JOIN TELEFONO ON ESTUDIANTE_PUEDE_TENER_REPRESENTANTE.CIR=TELEFONO.CI JOIN ESTUDIANTE" +
" ON ESTUDIANTE_PUEDE_TENER_REPRESENTANTE.CIE=ESTUDIANTE.CI  ");
        try{
            while(res.next()){
                Vector v = new Vector();
            v.add(res.getString(1));
            v.add(res.getString(2));
            v.add(res.getInt(3));
            v.add(res.getInt(4));
            v.add(res.getString(5));
            v.add(res.getInt(6));
            v.add(res.getInt(7));
            modelo.addRow(v);
            Tmodulo.setModel(modelo);
            }
        }catch (SQLException e){            
        }
}
        public void  FiltrarDatos(String Valor){
        DefaultTableModel modelo =(DefaultTableModel) Tmodulo.getModel();
        modelo.setRowCount(0);
        res = Conexiones.Conexion.Consulta(" SELECT P_NOMBRE,P_APELLIDO,PREF,NUMERO,PARENTESCO,ESTUDIANTE_PUEDE_TENER_REPRESENTANTE.CIR" +
" ,ESTUDIANTE.CI FROM PERSONA  JOIN ESTUDIANTE_PUEDE_TENER_REPRESENTANTE" +
" ON ESTUDIANTE_PUEDE_TENER_REPRESENTANTE.CIR=PERSONA.CI JOIN TELEFONO ON ESTUDIANTE_PUEDE_TENER_REPRESENTANTE.CIR=TELEFONO.CI JOIN ESTUDIANTE" +
" ON ESTUDIANTE_PUEDE_TENER_REPRESENTANTE.CIE=ESTUDIANTE.CI  WHERE ESTUDIANTE_PUEDE_TENER_REPRESENTANTE.CIR  LIKE'%"+Valor+"%'");
        try{
            while(res.next()){
                Vector v = new Vector();
             v.add(res.getString(1));
            v.add(res.getString(2));
            v.add(res.getInt(3));
            v.add(res.getInt(4));
            v.add(res.getString(5));
            v.add(res.getInt(6));
            v.add(res.getInt(7));
            modelo.addRow(v);
            Tmodulo.setModel(modelo);
            }
        }catch (SQLException e){            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VolverCurso = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tmodulo = new javax.swing.JTable();
        buscar = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        Bactualizar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 206, 209));

        VolverCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_arrow_64px.png"))); // NOI18N
        VolverCurso.setBorder(null);
        VolverCurso.setContentAreaFilled(false);
        VolverCurso.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                VolverCursoMouseMoved(evt);
            }
        });
        VolverCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverCursoActionPerformed(evt);
            }
        });

        Tmodulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Prefijo", "Número", "Parentesco", "Cedula", "CI Estudiante"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tmodulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TmoduloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tmodulo);

        buscar.setBackground(new java.awt.Color(204, 206, 209));
        buscar.setBorder(null);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarKeyTyped(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 51, 102));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_30px.png"))); // NOI18N
        jButton1.setToolTipText("Buscar Mediante Cedula del Representante"); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Bactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_refresh_32px.png"))); // NOI18N
        Bactualizar.setText("Actualizar");
        Bactualizar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Bactualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Bactualizar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Bactualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Bactualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BactualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BactualizarMouseExited(evt);
            }
        });
        Bactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BactualizarActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Lao UI", 1, 24)); // NOI18N
        jLabel20.setText("REPRESENTANTES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VolverCurso)
                        .addGap(106, 106, 106)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(Bactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(VolverCurso)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bactualizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverCursoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverCursoMouseMoved
        VolverCurso.setToolTipText("Volver");
    }//GEN-LAST:event_VolverCursoMouseMoved

    private void VolverCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverCursoActionPerformed
        dispose();
    }//GEN-LAST:event_VolverCursoActionPerformed

    private void TmoduloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TmoduloMouseClicked
      
    }//GEN-LAST:event_TmoduloMouseClicked

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        FiltrarDatos(buscar.getText());
    }//GEN-LAST:event_buscarKeyReleased

    private void buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyTyped

    }//GEN-LAST:event_buscarKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BactualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BactualizarMouseEntered
         
    }//GEN-LAST:event_BactualizarMouseEntered

    private void BactualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BactualizarMouseExited
        
    }//GEN-LAST:event_BactualizarMouseExited

    private void BactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BactualizarActionPerformed
        CargarDatos();
    }//GEN-LAST:event_BactualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstuyRepre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstuyRepre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstuyRepre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstuyRepre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EstuyRepre dialog = new EstuyRepre(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Bactualizar;
    public static javax.swing.JTable Tmodulo;
    public static javax.swing.JButton VolverCurso;
    public static javax.swing.JTextField buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
