/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Reporte.listadomodulos;

import Conexiones.Conexion;
import Controlador.fondo;
import Reporte.Secciones;
import Reporte.NotasEstudiantiles;
import Reporte.Constancia;
import Reporte.InformacionEstu;
import Reporte.SeccionesDisponibles;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.InputStream;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import vista.AperturaSeccion;
import vista.Inscripcion;
import vista.MostrarCurso;
import vista.PagoEstudiante;
import vista.Preinscripcion;
import vista.Recursos;
import vista.empleados;
import vista.mostrarempleados;
import vista.usuario;

/**
 *
 * @author FARMING
 */
public class menu extends javax.swing.JFrame {

    public InputStream foto1 = this.getClass().getResourceAsStream("/img/FONDO.png");
   
         /**
     * Creates new form menu
     */
    public menu() {

        this.setUndecorated(true);
        initComponents();
        setSize(1243, 800);
        this.setLocationRelativeTo(null);
        cargarImagen(Escritorio, foto1);
        

    }

    public void cargarImagen(javax.swing.JDesktopPane jDeskp, InputStream fileImagen) {
        try {
            BufferedImage image = ImageIO.read(fileImagen);
            Escritorio.setBorder(new fondo(image));
        } catch (Exception e) {
            System.out.println("Imagen no disponible");
        }
    }
 
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem1 = new javax.swing.JMenuItem();
        Escritorio = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        RCurso = new javax.swing.JMenuItem();
        Mcursos = new javax.swing.JMenuItem();
        AperturaSeccion = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        Mempleados = new javax.swing.JMenuItem();
        Mosempleados = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        JCursos = new javax.swing.JMenu();
        Bpreinscripcion = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        Binscripcion = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu4 = new javax.swing.JMenu();
        Busuario = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu5 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        SeccionesD = new javax.swing.JMenuItem();
        CursosD = new javax.swing.JMenuItem();
        CursosD1 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        SeccionesD2 = new javax.swing.JMenuItem();
        CursosD2 = new javax.swing.JMenuItem();
        EstudiantesA = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        BACKup = new javax.swing.JMenu();
        Busuario1 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_bookmark_64px.png"))); // NOI18N
        jButton1.setText("haz click aqui");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Escritorio.add(jButton1);
        jButton1.setBounds(550, 510, 110, 90);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Para ver los Modulos de los curso  ");
        Escritorio.add(jLabel1);
        jLabel1.setBounds(494, 440, 236, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eeeee.png"))); // NOI18N
        Escritorio.add(jLabel2);
        jLabel2.setBounds(480, 290, 770, 460);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sin título-1.png"))); // NOI18N
        Escritorio.add(jLabel3);
        jLabel3.setBounds(-50, 290, 510, 460);

        getContentPane().add(Escritorio);
        Escritorio.setBounds(0, 0, 1240, 740);

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 102));
        jMenuBar1.setBorder(null);

        jMenu1.setBackground(new java.awt.Color(22, 44, 81));
        jMenu1.setForeground(new java.awt.Color(0, 136, 205));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_bookmark_64px.png"))); // NOI18N
        jMenu1.setText("CURSOS");

        RCurso.setBackground(new java.awt.Color(153, 204, 255));
        RCurso.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        RCurso.setText("Nuevo Curso");
        RCurso.setBorder(null);
        RCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RCursoActionPerformed(evt);
            }
        });
        jMenu1.add(RCurso);

        Mcursos.setBackground(new java.awt.Color(153, 204, 255));
        Mcursos.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Mcursos.setText("Cursos Registrados");
        Mcursos.setBorder(null);
        Mcursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                McursosMouseClicked(evt);
            }
        });
        Mcursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                McursosActionPerformed(evt);
            }
        });
        jMenu1.add(Mcursos);

        AperturaSeccion.setBackground(new java.awt.Color(153, 204, 255));
        AperturaSeccion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        AperturaSeccion.setText("Apertura de Sección");
        AperturaSeccion.setBorder(null);
        AperturaSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AperturaSeccionActionPerformed(evt);
            }
        });
        jMenu1.add(AperturaSeccion);

        jSeparator5.setForeground(new java.awt.Color(0, 102, 153));
        jMenu1.add(jSeparator5);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(22, 44, 81));
        jMenu2.setForeground(new java.awt.Color(0, 136, 205));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_conference_64px.png"))); // NOI18N
        jMenu2.setText("EMPLEADOS");

        Mempleados.setBackground(new java.awt.Color(153, 204, 255));
        Mempleados.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Mempleados.setText("Nuevo Personal");
        Mempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MempleadosActionPerformed(evt);
            }
        });
        jMenu2.add(Mempleados);

        Mosempleados.setBackground(new java.awt.Color(153, 204, 255));
        Mosempleados.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Mosempleados.setText("Mostrar Empleados");
        Mosempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MosempleadosActionPerformed(evt);
            }
        });
        jMenu2.add(Mosempleados);

        jSeparator4.setForeground(new java.awt.Color(0, 102, 153));
        jMenu2.add(jSeparator4);

        jMenuBar1.add(jMenu2);

        JCursos.setBackground(new java.awt.Color(22, 44, 81));
        JCursos.setForeground(new java.awt.Color(0, 136, 205));
        JCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_pencil_64px.png"))); // NOI18N
        JCursos.setText("MATRICULACIÓN");

        Bpreinscripcion.setBackground(new java.awt.Color(153, 204, 255));
        Bpreinscripcion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Bpreinscripcion.setText("Preinscripciòn");
        Bpreinscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BpreinscripcionActionPerformed(evt);
            }
        });
        JCursos.add(Bpreinscripcion);

        jMenuItem6.setBackground(new java.awt.Color(153, 204, 255));
        jMenuItem6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItem6.setText("Pago Estudiantil");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        JCursos.add(jMenuItem6);

        Binscripcion.setBackground(new java.awt.Color(153, 204, 255));
        Binscripcion.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Binscripcion.setText("Inscripción");
        Binscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinscripcionActionPerformed(evt);
            }
        });
        JCursos.add(Binscripcion);

        jMenuItem7.setBackground(new java.awt.Color(153, 204, 255));
        jMenuItem7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jMenuItem7.setText("Nota Estudiantil");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        JCursos.add(jMenuItem7);

        jSeparator2.setForeground(new java.awt.Color(0, 102, 153));
        JCursos.add(jSeparator2);

        jMenuBar1.add(JCursos);

        jMenu4.setBackground(new java.awt.Color(22, 44, 81));
        jMenu4.setForeground(new java.awt.Color(0, 136, 205));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_administrator_male_64px.png"))); // NOI18N
        jMenu4.setText("USUARIOS");

        Busuario.setBackground(new java.awt.Color(153, 204, 255));
        Busuario.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Busuario.setText("Usuario");
        Busuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusuarioActionPerformed(evt);
            }
        });
        jMenu4.add(Busuario);

        jSeparator3.setForeground(new java.awt.Color(0, 102, 153));
        jMenu4.add(jSeparator3);

        jMenuBar1.add(jMenu4);

        jMenu5.setBackground(new java.awt.Color(22, 44, 81));
        jMenu5.setForeground(new java.awt.Color(0, 136, 205));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_opened_folder_64px.png"))); // NOI18N
        jMenu5.setText("REPORTES");

        jMenu3.setBorder(null);
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_folder_16px.png"))); // NOI18N
        jMenu3.setText("Curso");
        jMenu3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        SeccionesD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SeccionesD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_folder_16px.png"))); // NOI18N
        SeccionesD.setText("Status de la Sección");
        SeccionesD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeccionesDActionPerformed(evt);
            }
        });
        jMenu3.add(SeccionesD);

        CursosD.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CursosD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_folder_16px.png"))); // NOI18N
        CursosD.setText("Listado Estudiantil");
        CursosD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursosDActionPerformed(evt);
            }
        });
        jMenu3.add(CursosD);

        CursosD1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CursosD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_folder_16px.png"))); // NOI18N
        CursosD1.setText("Notas Estudiantiles");
        CursosD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursosD1ActionPerformed(evt);
            }
        });
        jMenu3.add(CursosD1);

        jMenu5.add(jMenu3);

        jMenu8.setBorder(null);
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_folder_16px.png"))); // NOI18N
        jMenu8.setText("Pago");
        jMenu8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        SeccionesD2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        SeccionesD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_folder_16px.png"))); // NOI18N
        SeccionesD2.setText("Pago de Inscripción");
        SeccionesD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeccionesD2ActionPerformed(evt);
            }
        });
        jMenu8.add(SeccionesD2);

        CursosD2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CursosD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_folder_16px.png"))); // NOI18N
        CursosD2.setText("Constancia de Estudio");
        CursosD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursosD2ActionPerformed(evt);
            }
        });
        jMenu8.add(CursosD2);

        jMenu5.add(jMenu8);

        EstudiantesA.setBackground(new java.awt.Color(153, 204, 255));
        EstudiantesA.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        EstudiantesA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_folder_16px.png"))); // NOI18N
        EstudiantesA.setText("Información del Estudiante");
        EstudiantesA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudiantesAActionPerformed(evt);
            }
        });
        jMenu5.add(EstudiantesA);

        jSeparator6.setForeground(new java.awt.Color(0, 102, 153));
        jMenu5.add(jSeparator6);

        jMenuBar1.add(jMenu5);

        BACKup.setBackground(new java.awt.Color(22, 44, 81));
        BACKup.setForeground(new java.awt.Color(0, 136, 205));
        BACKup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_services_64px.png"))); // NOI18N
        BACKup.setText("CONFIGURACIÓN");

        Busuario1.setBackground(new java.awt.Color(153, 204, 255));
        Busuario1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Busuario1.setText("Backup y Restore");
        Busuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Busuario1ActionPerformed(evt);
            }
        });
        BACKup.add(Busuario1);

        jSeparator7.setForeground(new java.awt.Color(0, 102, 153));
        BACKup.add(jSeparator7);

        jMenuBar1.add(BACKup);

        jMenu6.setForeground(new java.awt.Color(0, 136, 205));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_exit_52px.png"))); // NOI18N
        jMenu6.setText("CERRAR SESION");

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BpreinscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BpreinscripcionActionPerformed
        Preinscripcion re = new Preinscripcion();
        Escritorio.add(re);
        re.show();
    }//GEN-LAST:event_BpreinscripcionActionPerformed


    private void McursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_McursosMouseClicked

    }//GEN-LAST:event_McursosMouseClicked

    private void McursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_McursosActionPerformed
        MostrarCurso re = new MostrarCurso();
        Escritorio.add(re);
        re.show();

    }//GEN-LAST:event_McursosActionPerformed

    private void MempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MempleadosActionPerformed
        empleados re = new empleados();
        Escritorio.add(re);
        re.show();
    }//GEN-LAST:event_MempleadosActionPerformed

    private void MosempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MosempleadosActionPerformed
        mostrarempleados re = new mostrarempleados();
        Escritorio.add(re);
        re.show();
    }//GEN-LAST:event_MosempleadosActionPerformed

    private void BusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusuarioActionPerformed
        usuario re = new usuario();
        Escritorio.add(re);
        re.show();
    }//GEN-LAST:event_BusuarioActionPerformed

    private void AperturaSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AperturaSeccionActionPerformed
        AperturaSeccion re = new AperturaSeccion();
        Escritorio.add(re);
        re.show();

    }//GEN-LAST:event_AperturaSeccionActionPerformed

    private void BinscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinscripcionActionPerformed
        Inscripcion re = new Inscripcion();
        Escritorio.add(re);
        re.show();
    }//GEN-LAST:event_BinscripcionActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
     PagoEstudiante re = new PagoEstudiante();
        Escritorio.add(re);
        re.show();

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void EstudiantesAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudiantesAActionPerformed
        Frame f = JOptionPane.getFrameForComponent(this);
        new InformacionEstu(f, true).setVisible(true);
    }//GEN-LAST:event_EstudiantesAActionPerformed

    private void CursosDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursosDActionPerformed
        Frame f = JOptionPane.getFrameForComponent(this);
        new Secciones (f, true).setVisible(true);
    }//GEN-LAST:event_CursosDActionPerformed

    private void SeccionesDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeccionesDActionPerformed
        Frame f = JOptionPane.getFrameForComponent(this);
        new SeccionesDisponibles(f, true).setVisible(true);
    }//GEN-LAST:event_SeccionesDActionPerformed

    private void RCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RCursoActionPerformed
        Recursos re = new Recursos();
        Escritorio.add(re);
        re.show();

    }//GEN-LAST:event_RCursoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       NotasEstudiantile re = new NotasEstudiantile();
        Escritorio.add(re);
        re.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void Busuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Busuario1ActionPerformed
        //BACK UP
        Backup re = new Backup();
        Escritorio.add(re);
        re.show();
        
        
    }//GEN-LAST:event_Busuario1ActionPerformed

    private void CursosD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursosD1ActionPerformed
        Frame f = JOptionPane.getFrameForComponent(this);
        new NotasEstudiantiles(f, true).setVisible(true);
    }//GEN-LAST:event_CursosD1ActionPerformed

    private void SeccionesD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeccionesD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeccionesD2ActionPerformed

    private void CursosD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursosD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CursosD2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Frame f = JOptionPane.getFrameForComponent(this);
        new listadomodulos(f, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JMenuItem AperturaSeccion;
    public static javax.swing.JMenu BACKup;
    public static javax.swing.JMenuItem Binscripcion;
    public static javax.swing.JMenuItem Bpreinscripcion;
    public static javax.swing.JMenuItem Busuario;
    public static javax.swing.JMenuItem Busuario1;
    public static javax.swing.JMenuItem CursosD;
    public static javax.swing.JMenuItem CursosD1;
    public static javax.swing.JMenuItem CursosD2;
    public static javax.swing.JDesktopPane Escritorio;
    public static javax.swing.JMenuItem EstudiantesA;
    public static javax.swing.JMenu JCursos;
    public static javax.swing.JMenuItem Mcursos;
    public static javax.swing.JMenuItem Mempleados;
    public static javax.swing.JMenuItem Mosempleados;
    public static javax.swing.JMenuItem RCurso;
    public static javax.swing.JMenuItem SeccionesD;
    public static javax.swing.JMenuItem SeccionesD2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JMenu jMenu1;
    public static javax.swing.JMenu jMenu2;
    public static javax.swing.JMenu jMenu3;
    public static javax.swing.JMenu jMenu4;
    public static javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    public static javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    public static javax.swing.JMenuItem jMenuItem6;
    public static javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    public static javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    // End of variables declaration//GEN-END:variables
}
