/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Conexiones.BDConexion;
import Controlador.SoloLetras;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
/**
 *
 * @author rosan
 */
public class ModificarUsuario extends javax.swing.JDialog {
static ResultSet res;
    /**
     * Creates new form ModificarUsuario
     */
    public ModificarUsuario(java.awt.Frame parent, boolean modal) {
       super(parent, modal);
         initComponents();
           this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Ciusuario = new javax.swing.JTextField();
        Reusuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Respuestas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Cargo = new javax.swing.JComboBox<>();
        Recontraseña = new javax.swing.JPasswordField();
        PDseguridad = new javax.swing.JTextField();
        CodExiste = new javax.swing.JTextField();
        GuardarCambiosUsu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        BuscarUsu = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("CI:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(126, 98, 17, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Usuario:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(101, 144, 46, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(82, 181, 66, 17);

        Ciusuario.setBorder(null);
        Ciusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiusuarioActionPerformed(evt);
            }
        });
        Ciusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CiusuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CiusuarioKeyTyped(evt);
            }
        });
        jPanel1.add(Ciusuario);
        Ciusuario.setBounds(153, 99, 145, 17);

        Reusuario.setBorder(null);
        Reusuario.setEnabled(false);
        Reusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReusuarioActionPerformed(evt);
            }
        });
        Reusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ReusuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ReusuarioKeyTyped(evt);
            }
        });
        jPanel1.add(Reusuario);
        Reusuario.setBounds(157, 146, 145, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Preguntas de Seguridad");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(48, 273, 133, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Respuesta:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(282, 269, 60, 17);

        Respuestas.setBorder(null);
        Respuestas.setEnabled(false);
        Respuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespuestasActionPerformed(evt);
            }
        });
        Respuestas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RespuestasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RespuestasKeyTyped(evt);
            }
        });
        jPanel1.add(Respuestas);
        Respuestas.setBounds(282, 297, 154, 14);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_user_groups_32px.png"))); // NOI18N
        jLabel8.setText("Usuario");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(163, 28, 117, 32);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Cargo");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(141, 373, 34, 17);

        Cargo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cargo.setForeground(new java.awt.Color(102, 102, 102));
        Cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secretaria", "administrador" }));
        Cargo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoActionPerformed(evt);
            }
        });
        jPanel1.add(Cargo);
        Cargo.setBounds(185, 369, 161, 25);

        Recontraseña.setBorder(null);
        Recontraseña.setEnabled(false);
        Recontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RecontraseñaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RecontraseñaKeyTyped(evt);
            }
        });
        jPanel1.add(Recontraseña);
        Recontraseña.setBounds(157, 183, 145, 14);

        PDseguridad.setBorder(null);
        PDseguridad.setEnabled(false);
        PDseguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDseguridadActionPerformed(evt);
            }
        });
        PDseguridad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PDseguridadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PDseguridadKeyTyped(evt);
            }
        });
        jPanel1.add(PDseguridad);
        PDseguridad.setBounds(48, 301, 152, 14);

        CodExiste.setEditable(false);
        CodExiste.setBackground(new java.awt.Color(255, 255, 255));
        CodExiste.setForeground(new java.awt.Color(51, 51, 51));
        CodExiste.setBorder(null);
        CodExiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodExisteActionPerformed(evt);
            }
        });
        jPanel1.add(CodExiste);
        CodExiste.setBounds(320, 166, 108, 14);

        GuardarCambiosUsu.setBackground(new java.awt.Color(142, 252, 199));
        GuardarCambiosUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_26px_1.png"))); // NOI18N
        GuardarCambiosUsu.setText("Guardar");
        GuardarCambiosUsu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        GuardarCambiosUsu.setEnabled(false);
        GuardarCambiosUsu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GuardarCambiosUsu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        GuardarCambiosUsu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GuardarCambiosUsu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                GuardarCambiosUsuMouseMoved(evt);
            }
        });
        GuardarCambiosUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuardarCambiosUsuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GuardarCambiosUsuMouseExited(evt);
            }
        });
        GuardarCambiosUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarCambiosUsuActionPerformed(evt);
            }
        });
        jPanel1.add(GuardarCambiosUsu);
        GuardarCambiosUsu.setBounds(182, 481, 100, 61);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_identification_documents_24px.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(92, 90, 24, 26);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_user_32px.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(63, 130, 32, 32);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_key_2_32px.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(44, 166, 32, 32);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_security_lock_32px.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 273, 32, 32);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_security_lock_32px.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(241, 269, 32, 32);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_microsoft_admin_30px.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(101, 364, 30, 30);

        jSeparator2.setBackground(new java.awt.Color(22, 44, 81));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(153, 122, 145, 2);

        jSeparator3.setBackground(new java.awt.Color(22, 44, 81));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(157, 204, 145, 8);

        jSeparator4.setBackground(new java.awt.Color(22, 44, 81));
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(282, 317, 152, 15);

        jSeparator5.setBackground(new java.awt.Color(22, 44, 81));
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(48, 321, 146, 11);

        jSeparator6.setBackground(new java.awt.Color(22, 44, 81));
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(155, 166, 147, 8);

        BuscarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_30px.png"))); // NOI18N
        BuscarUsu.setBorder(null);
        BuscarUsu.setContentAreaFilled(false);
        BuscarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarUsuActionPerformed(evt);
            }
        });
        jPanel1.add(BuscarUsu);
        BuscarUsu.setBounds(316, 93, 31, 31);

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 102));
        jButton2.setText("x");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(423, 11, 30, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CiusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CiusuarioActionPerformed

    private void CiusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CiusuarioKeyReleased

    }//GEN-LAST:event_CiusuarioKeyReleased

    private void CiusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CiusuarioKeyTyped
        char car = evt.getKeyChar();
        if (Ciusuario.getText().length() >= 8) {
            evt.consume();
        }
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_CiusuarioKeyTyped

    private void ReusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReusuarioActionPerformed

    private void ReusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReusuarioKeyReleased

    }//GEN-LAST:event_ReusuarioKeyReleased

    private void ReusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReusuarioKeyTyped
        char b = evt.getKeyChar();
        if (Reusuario.getText().length() >= 10) {
            evt.consume();
        }
        if ((b < 'a' || b > 'z') && (b < '0' || b > '9') && (b < 'A' || b > 'Z')&& (b != 'ñ') && (b != 'Ñ')) {
            evt.consume();
        }
    }//GEN-LAST:event_ReusuarioKeyTyped

    private void RespuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespuestasActionPerformed

    }//GEN-LAST:event_RespuestasActionPerformed

    private void RespuestasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RespuestasKeyReleased

    }//GEN-LAST:event_RespuestasKeyReleased

    private void RespuestasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RespuestasKeyTyped
        Character s = evt.getKeyChar();
        char b = evt.getKeyChar();
        if (Respuestas.getText().length() >= 15) {
            evt.consume();
        }
        if ((b < 'a' || b > 'z') && (b < '0' || b > '9') && (b < 'A' || b > 'Z') && (s != 'ñ') && (s != 'Ñ')&& (s != KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_RespuestasKeyTyped

    private void CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargoActionPerformed

    private void RecontraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RecontraseñaKeyReleased

    }//GEN-LAST:event_RecontraseñaKeyReleased

    private void RecontraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RecontraseñaKeyTyped
        char b = evt.getKeyChar();
        if (Recontraseña.getText().length() >= 10) {
            evt.consume();
        }
        if ((b < 'a' || b > 'z')&& (b < 'A' || b > 'Z') && (b < '0' || b > '9')&& (b != 'ñ') && (b != 'Ñ')) {
            evt.consume();
        }
    }//GEN-LAST:event_RecontraseñaKeyTyped

    private void PDseguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDseguridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDseguridadActionPerformed

    private void PDseguridadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PDseguridadKeyReleased

    }//GEN-LAST:event_PDseguridadKeyReleased

    private void PDseguridadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PDseguridadKeyTyped
        SoloLetras.letrasYespacio(evt, PDseguridad.getText());
    }//GEN-LAST:event_PDseguridadKeyTyped

    private void CodExisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodExisteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodExisteActionPerformed

    private void GuardarCambiosUsuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarCambiosUsuMouseMoved

    }//GEN-LAST:event_GuardarCambiosUsuMouseMoved

    private void GuardarCambiosUsuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarCambiosUsuMouseEntered

    }//GEN-LAST:event_GuardarCambiosUsuMouseEntered

    private void GuardarCambiosUsuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarCambiosUsuMouseExited

    }//GEN-LAST:event_GuardarCambiosUsuMouseExited

    private void GuardarCambiosUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarCambiosUsuActionPerformed
        try{
            PreparedStatement pps = Conexiones.Conexion.getConexion().prepareStatement("update USUARIO set USUARIO='" +
                Reusuario.getText() + "', CONTRASEÑA='" + Recontraseña.getText() + "', TIPO_USU='"
                + Cargo.getSelectedItem() + "', PREGUNTA_SECRETA='"
                + PDseguridad.getText() + "', RESPUESTA_sEC='" + Respuestas.getText() +
                "' where CI='" + Ciusuario.getText() + "'");
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "LOS DATOS HAN SIDO MODIFICADOS");

            Reusuario.setText("");
            Recontraseña.setText("");
            PDseguridad.setText("");
            Respuestas.setText("");
            Cargo.setSelectedItem("");

            Reusuario.requestFocus();
            Recontraseña.requestFocus();
            PDseguridad.requestFocus();
            Respuestas.requestFocus();
            Cargo.requestFocus();
            Ciusuario.requestFocus();

        }catch(SQLException e){
        }
        Ciusuario.setText("");
        Reusuario.setEnabled(false);
        Recontraseña.setEnabled(false);
        PDseguridad.setEnabled(false);
        Respuestas.setEnabled(false);
        Cargo.setEnabled(false);
        this.GuardarCambiosUsu.setVisible(false);
        this.BuscarUsu.setVisible(false);
    }//GEN-LAST:event_GuardarCambiosUsuActionPerformed

    private void BuscarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarUsuActionPerformed
        if(Ciusuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Coloque Bien sus Datos","Error",JOptionPane.ERROR_MESSAGE);
            Ciusuario.setText("");
            Ciusuario.requestFocus();
        }else{
            try{
                String b;
                BDConexion.BuscarUsuario(Integer.parseInt(Ciusuario.getText()));
                b=Ciusuario.getText();
                Reusuario.setText("");
                Recontraseña.setText("");
                Cargo.setSelectedItem("");
                PDseguridad.setText("");
                Respuestas.setText("");

                Ciusuario.setText("");

                Reusuario.requestFocus();
                Recontraseña.requestFocus();
                PDseguridad.requestFocus();
                Respuestas.requestFocus();
                Cargo.requestFocus();
                Ciusuario.requestFocus();
                res= Conexiones.Conexion.Consulta("select * from USUARIO");
                while(res.next()){
                    if(res.getString(6).equals(b)){
                        JOptionPane.showMessageDialog(null,"Datos Encontrados");
                        Reusuario.setText(res.getString(1));
                        Recontraseña.setText(res.getString(2));
                        Cargo.setSelectedItem(res.getString(3));
                        PDseguridad.setText(res.getString(4));

                        Respuestas.setText(res.getString(5));

                        Ciusuario.setText(res.getString(6));

                    }else{
                        System.out.println("datos encontrados");
                    }

                }
                Ciusuario.setEditable(false);
                Reusuario.setEnabled(true);
                Recontraseña.setEnabled(true);
                PDseguridad.setEnabled(true);
                Respuestas.setEnabled(true);
                Cargo.setEnabled(true);
                  

                this.GuardarCambiosUsu.setVisible(true);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_BuscarUsuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarUsuario dialog = new ModificarUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarUsu;
    public static javax.swing.JComboBox<String> Cargo;
    public static javax.swing.JTextField Ciusuario;
    private javax.swing.JTextField CodExiste;
    public static javax.swing.JButton GuardarCambiosUsu;
    public static javax.swing.JTextField PDseguridad;
    public static javax.swing.JPasswordField Recontraseña;
    public static javax.swing.JTextField Respuestas;
    public static javax.swing.JTextField Reusuario;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
