/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Conexiones.BDConexion;
import Controlador.SoloLetras;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 

/**
 *
 * @author rosan
 */
public class Moduls extends javax.swing.JDialog {
static ResultSet res;
    /**
     * Creates new form Moduls
     */
    public Moduls(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
       initComponents();
           this.setLocationRelativeTo(null);
        
        CargarDatos();
       
        this.CAMBIOS.setVisible(false);
    }
    public void Validacion() {
     String mensaje=BDConexion.bucarCi(CodigoCurso.getText());
     if(mensaje.equals("El Codigo Existe")){
         CodExiste.setText("Codigo Registrado");   
         SaveModulo.setEnabled(true);
     }else if(CodigoCurso.getText().isEmpty()){
     CodExiste.setText("");
         
     }else{
        CodExiste.setText("Codigo no Registrado"); 
               SaveModulo.setEnabled(false); 
             }
}
public void HabilitarBoton(){
        if(CodigoCurso.getText().length()==4&&!modulo.getText().isEmpty()){
            SaveModulo.setEnabled(true);
        }else{
            SaveModulo.setEnabled(false);
        }
    }
public void  CargarDatos(){
        DefaultTableModel modelo =(DefaultTableModel) Tmodulo.getModel();
        modelo.setRowCount(0);
        res = Conexiones.Conexion.Consulta("SELECT * FROM MODULO");
        try{
            while(res.next()){
                Vector v = new Vector();
            v.add(res.getInt(1));
            v.add(res.getInt(2));
            v.add(res.getString(3));
            modelo.addRow(v);
            Tmodulo.setModel(modelo);
            }
        }catch (SQLException e){            
        }
}
        public void  FiltrarDatos(String Valor){
        DefaultTableModel modelo =(DefaultTableModel) Tmodulo.getModel();
        modelo.setRowCount(0);
        res = Conexiones.Conexion.Consulta("SELECT * FROM MODULO WHERE MODULO.ID_CURSO LIKE'%"+Valor+"%'");
        try{
            while(res.next()){
                Vector v = new Vector();
            v.add(res.getInt(1));
            v.add(res.getInt(2));
            v.add(res.getString(3));
            modelo.addRow(v);
            Tmodulo.setModel(modelo);
            }
        }catch (SQLException e){            
        }
    }
        public void GuardarModulo(){
            if (CodigoCurso.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this,"rellene todos los campos obligatorios",   "informacion", JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                String cod,mod;
                BDConexion.EntradaModulo(

                    cod=CodigoCurso.getText(),
                    mod=modulo.getText());
                JOptionPane.showMessageDialog(null, "Guardado Exitoso");
                modulo.setText("");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,  ex);
            }

        }
        }
        public void CambiosModulo(){
            try {
            PreparedStatement pps = Conexiones.Conexion.getConexion().prepareStatement("update MODULO set MOD_CURS='" + modulo.getText() +
                "' where ID_CURSO='" + CodigoCurso.getText() + "' AND ID_MODULOS= '" + id.getText() + "'");
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "LOS DATOS HAN SIDO MODIFICADOS");

            modulo.setText("");

            modulo.requestFocus();

        } catch (SQLException e) {
        }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CodigoCurso = new javax.swing.JTextField();
        modulo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        VolverCurso = new javax.swing.JButton();
        SaveModulo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        CodExiste = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tmodulo = new javax.swing.JTable();
        CAMBIOS = new javax.swing.JButton();
        buscar = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Bactualizar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 206, 209));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Código");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Contenido");

        CodigoCurso.setBackground(new java.awt.Color(204, 206, 209));
        CodigoCurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CodigoCurso.setBorder(null);
        CodigoCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CodigoCursoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CodigoCursoKeyTyped(evt);
            }
        });

        modulo.setBackground(new java.awt.Color(204, 206, 209));
        modulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modulo.setBorder(null);
        modulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                moduloKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                moduloKeyTyped(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 204, 102));
        jSeparator1.setForeground(new java.awt.Color(255, 204, 102));

        jSeparator2.setBackground(new java.awt.Color(255, 204, 102));
        jSeparator2.setForeground(new java.awt.Color(255, 204, 102));

        VolverCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_arrow_64px.png"))); // NOI18N
        VolverCurso.setBorder(null);
        VolverCurso.setContentAreaFilled(false);
        VolverCurso.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                VolverCursoMouseMoved(evt);
            }
        });
        VolverCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverCursoActionPerformed(evt);
            }
        });

        SaveModulo.setBackground(new java.awt.Color(142, 252, 199));
        SaveModulo.setForeground(new java.awt.Color(204, 204, 204));
        SaveModulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_26px_1.png"))); // NOI18N
        SaveModulo.setText("Guardar");
        SaveModulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        SaveModulo.setEnabled(false);
        SaveModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveModuloActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_list_30px.png"))); // NOI18N

        CodExiste.setEditable(false);
        CodExiste.setBackground(new java.awt.Color(204, 206, 209));
        CodExiste.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CodExiste.setForeground(new java.awt.Color(255, 255, 255));
        CodExiste.setBorder(null);

        Tmodulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Codigo Curso", "Modulos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tmodulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TmoduloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tmodulo);

        CAMBIOS.setBackground(new java.awt.Color(142, 252, 199));
        CAMBIOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_26px_1.png"))); // NOI18N
        CAMBIOS.setText("Guardar ");
        CAMBIOS.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        CAMBIOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAMBIOSActionPerformed(evt);
            }
        });

        buscar.setBackground(new java.awt.Color(204, 206, 209));
        buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscar.setBorder(null);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                buscarKeyTyped(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(255, 204, 102));
        jSeparator3.setForeground(new java.awt.Color(255, 204, 102));

        id.setEditable(false);
        id.setBackground(new java.awt.Color(204, 206, 209));
        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.setBorder(null);
        id.setDisabledTextColor(new java.awt.Color(255, 102, 0));
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_30px.png"))); // NOI18N
        jButton1.setToolTipText("Buscar Mediante Codigo del Curso"); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Bactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_refresh_32px.png"))); // NOI18N
        Bactualizar.setText("Actualizar");
        Bactualizar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Bactualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Bactualizar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Bactualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Bactualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BactualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BactualizarMouseExited(evt);
            }
        });
        Bactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BactualizarActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setText("Modulos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(VolverCurso)
                .addGap(247, 247, 247)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addGap(6, 6, 6)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(482, 482, 482)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel12))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(CodExiste, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(modulo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(CAMBIOS))
                    .addComponent(SaveModulo))
                .addGap(317, 317, 317)
                .addComponent(Bactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VolverCurso)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel12)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(CodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CodExiste, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(11, 11, 11)
                        .addComponent(modulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CAMBIOS, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bactualizar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void BactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BactualizarActionPerformed
        CargarDatos();
    }//GEN-LAST:event_BactualizarActionPerformed

    private void BactualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BactualizarMouseExited

    }//GEN-LAST:event_BactualizarMouseExited

    private void BactualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BactualizarMouseEntered

    }//GEN-LAST:event_BactualizarMouseEntered

    private void TmoduloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TmoduloMouseClicked
        int seleccion=Tmodulo.getSelectedRow();
        id.setText(Tmodulo.getValueAt(seleccion,0).toString());
        CodigoCurso.setText(Tmodulo.getValueAt(seleccion,1).toString());
        modulo.setText(Tmodulo.getValueAt(seleccion,2).toString());

        this.CAMBIOS.setVisible(true);
        SaveModulo.setVisible(false);
    }//GEN-LAST:event_TmoduloMouseClicked

    private void CAMBIOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAMBIOSActionPerformed
        CambiosModulo();
    }//GEN-LAST:event_CAMBIOSActionPerformed

    private void moduloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moduloKeyTyped
        SoloLetras.letrasYespacio(evt, modulo.getText());
    }//GEN-LAST:event_moduloKeyTyped

    private void moduloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_moduloKeyReleased
        HabilitarBoton();
    }//GEN-LAST:event_moduloKeyReleased

    private void buscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyTyped

    }//GEN-LAST:event_buscarKeyTyped

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        FiltrarDatos(buscar.getText());
    }//GEN-LAST:event_buscarKeyReleased

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void VolverCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverCursoActionPerformed
        dispose();
    }//GEN-LAST:event_VolverCursoActionPerformed

    private void VolverCursoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverCursoMouseMoved
        VolverCurso.setToolTipText("Volver");
    }//GEN-LAST:event_VolverCursoMouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SaveModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveModuloActionPerformed
        GuardarModulo();
    }//GEN-LAST:event_SaveModuloActionPerformed

    private void CodigoCursoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoCursoKeyTyped
        char car = evt.getKeyChar();
        if(CodigoCurso.getText().length()>=4) evt.consume();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_CodigoCursoKeyTyped

    private void CodigoCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoCursoKeyReleased
        HabilitarBoton();
        Validacion();
    }//GEN-LAST:event_CodigoCursoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moduls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moduls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moduls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moduls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Moduls dialog = new Moduls(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Bactualizar;
    public static javax.swing.JButton CAMBIOS;
    private javax.swing.JTextField CodExiste;
    public static javax.swing.JTextField CodigoCurso;
    public static javax.swing.JButton SaveModulo;
    public static javax.swing.JTable Tmodulo;
    public static javax.swing.JButton VolverCurso;
    public static javax.swing.JTextField buscar;
    public static javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JTextField modulo;
    // End of variables declaration//GEN-END:variables
}
