/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Conexiones.BDConexion;
import Controlador.SoloLetras;
import java.awt.Frame;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rosan
 */
public class usuario extends javax.swing.JInternalFrame {
 static ResultSet res;
    

    
    public usuario() {
       
        initComponents();
        setSize(1245, 740);
         
        CargarDatosUsuario();
        
          
        Ciusuario.setText(adm.Texto2);
     
      
        Validacion();
        
    }



    public void Respu() {
        if (!PDseguridad.getText().isEmpty()) {
            Respuestas.setEnabled(true);
          
        }else{
            Respuestas.setEnabled(false);
        }
               
              
        
    }
    public void R(){
         if(!Respuestas.getText().isEmpty()){
          
            GuardarUsuario.setEnabled(true);
        }else{
             GuardarUsuario.setEnabled(false);
         }
    }

    public void Validacion() {
        String mensaje = BDConexion.bucarCiAdmin(Ciusuario.getText());
        if (mensaje.equals("La Cedula ya Existe")) {
            CodExiste.setText("Administrativo");
           Reusuario.setEditable(true);
            
           Reusuario.setEnabled(true);
           
        } else if (Ciusuario.getText().isEmpty()) {
            CodExiste.setText("");

        } else {
            CodExiste.setText("Cedula no Administrativa");
           Reusuario.setEditable(false);
         
            
        }

        
    }
    public void Validacion2() {
        String mensaje = BDConexion.bucarCedulaUsuario(Ciusuario.getText());
        if (mensaje.equals("La Cedula ya Existe")) {
            Cexiste.setText("Usuario Registrado");
            
              Respuestas.setEnabled(false);
             Reusuario.setEnabled(false);
          Recontraseña.setEnabled(false);
            PDseguridad.setEnabled(false);
            Cargo.setEnabled(false);   
           
           
        } else if (Ciusuario.getText().isEmpty()) {
            CodExiste.setText("");

        } else {
            Cexiste.setText("");
          
             Reusuario.setEnabled(true);
          
            
        }

        
    }

    public void ValidacionUsuario() {
        String mensaje = BDConexion.buscarUsuario(Reusuario.getText());
        if (mensaje.equals("Usuario ya Existe")) {
            usu.setText(" Registrado");
             Recontraseña.setEnabled(false);
            PDseguridad.setEnabled(false);
            Cargo.setEnabled(false);   
            
        } else if (Reusuario.getText().isEmpty()) {
            usu.setText("");

        } else {
            usu.setText(" no Registrado");
             
            Recontraseña.setEnabled(true);
            PDseguridad.setEnabled(true);
            Cargo.setEnabled(true);
            
            
//           if (!Reusuario.getText().isEmpty() && !Recontraseña.getText().isEmpty() && !PDseguridad.getText().isEmpty() && !Respuestas.getText().isEmpty()) {
//                GuardarUsuario.setEnabled(true);
//            }
        }
    }

    public void CargarDatosUsuario() {
        DefaultTableModel modelo = (DefaultTableModel) UsuariosRegistrados.getModel();
        modelo.setRowCount(0);
        res = Conexiones.Conexion.Consulta("SELECT USUARIO,TIPO_USU,CI FROM USUARIO");
        try {
            while (res.next()) {
                Vector v = new Vector();
                v.add(res.getString(1));
                v.add(res.getString(2));
                v.add(res.getInt(3));

                modelo.addRow(v);
                UsuariosRegistrados.setModel(modelo);
            }
        } catch (SQLException e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inferior = new javax.swing.JPanel();
        pinferior = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UsuariosRegistrados = new javax.swing.JTable();
        Usuarios = new javax.swing.JLabel();
        ActualizarUsu = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Ciusuario = new javax.swing.JTextField();
        Reusuario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Respuestas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        GuardarUsuario = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Cargo = new javax.swing.JComboBox<>();
        Obligatorios = new javax.swing.JLabel();
        Obligatorios1 = new javax.swing.JLabel();
        Obligatorios2 = new javax.swing.JLabel();
        Obligatorios3 = new javax.swing.JLabel();
        Obligatorios7 = new javax.swing.JLabel();
        Recontraseña = new javax.swing.JPasswordField();
        PDseguridad = new javax.swing.JTextField();
        CodExiste = new javax.swing.JTextField();
        usu = new javax.swing.JTextField();
        Cexiste = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        BuscarUsu = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(248, 247, 247));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Registro de Usuario");
        getContentPane().setLayout(null);

        inferior.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout inferiorLayout = new javax.swing.GroupLayout(inferior);
        inferior.setLayout(inferiorLayout);
        inferiorLayout.setHorizontalGroup(
            inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        inferiorLayout.setVerticalGroup(
            inferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(inferior);
        inferior.setBounds(0, 0, 1240, 40);

        pinferior.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout pinferiorLayout = new javax.swing.GroupLayout(pinferior);
        pinferior.setLayout(pinferiorLayout);
        pinferiorLayout.setHorizontalGroup(
            pinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1510, Short.MAX_VALUE)
        );
        pinferiorLayout.setVerticalGroup(
            pinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(pinferior);
        pinferior.setBounds(0, 660, 1510, 50);

        UsuariosRegistrados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UsuariosRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Tipo de Usuario", "CI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UsuariosRegistrados.setGridColor(new java.awt.Color(0, 0, 0));
        UsuariosRegistrados.setRowHeight(25);
        UsuariosRegistrados.setSelectionBackground(new java.awt.Color(255, 0, 51));
        jScrollPane1.setViewportView(UsuariosRegistrados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 190, 400, 291);

        Usuarios.setBackground(new java.awt.Color(255, 255, 255));
        Usuarios.setFont(new java.awt.Font("Lao UI", 1, 24)); // NOI18N
        Usuarios.setForeground(new java.awt.Color(255, 255, 255));
        Usuarios.setText("USUARIOS REGISTRADOS");
        getContentPane().add(Usuarios);
        Usuarios.setBounds(130, 140, 310, 32);

        ActualizarUsu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ActualizarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_refresh_32px.png"))); // NOI18N
        ActualizarUsu.setText("Actualizar");
        ActualizarUsu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ActualizarUsu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ActualizarUsu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ActualizarUsu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ActualizarUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ActualizarUsuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ActualizarUsuMouseExited(evt);
            }
        });
        ActualizarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarUsuActionPerformed(evt);
            }
        });
        getContentPane().add(ActualizarUsu);
        ActualizarUsu.setBounds(90, 500, 101, 60);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("CI:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Usuario:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Contraseña:");

        Ciusuario.setBorder(null);
        Ciusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiusuarioActionPerformed(evt);
            }
        });
        Ciusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CiusuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CiusuarioKeyTyped(evt);
            }
        });

        Reusuario.setBorder(null);
        Reusuario.setEnabled(false);
        Reusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReusuarioActionPerformed(evt);
            }
        });
        Reusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ReusuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ReusuarioKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Preguntas de Seguridad");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Respuesta:");

        Respuestas.setBorder(null);
        Respuestas.setEnabled(false);
        Respuestas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespuestasActionPerformed(evt);
            }
        });
        Respuestas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RespuestasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RespuestasKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_user_groups_32px.png"))); // NOI18N
        jLabel8.setText("Usuario");

        GuardarUsuario.setBackground(new java.awt.Color(142, 252, 199));
        GuardarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_save_26px_1.png"))); // NOI18N
        GuardarUsuario.setText("Guardar");
        GuardarUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        GuardarUsuario.setEnabled(false);
        GuardarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        GuardarUsuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        GuardarUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        GuardarUsuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                GuardarUsuarioMouseMoved(evt);
            }
        });
        GuardarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GuardarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GuardarUsuarioMouseExited(evt);
            }
        });
        GuardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarUsuarioActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Cargo");

        Cargo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cargo.setForeground(new java.awt.Color(102, 102, 102));
        Cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Secretaria", "administrador" }));
        Cargo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargoActionPerformed(evt);
            }
        });

        Obligatorios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Obligatorios.setForeground(new java.awt.Color(204, 0, 51));
        Obligatorios.setText("*");
        Obligatorios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ObligatoriosMouseMoved(evt);
            }
        });

        Obligatorios1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Obligatorios1.setForeground(new java.awt.Color(204, 0, 51));
        Obligatorios1.setText("*");
        Obligatorios1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Obligatorios1MouseMoved(evt);
            }
        });

        Obligatorios2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Obligatorios2.setForeground(new java.awt.Color(204, 0, 51));
        Obligatorios2.setText("*");
        Obligatorios2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Obligatorios2MouseMoved(evt);
            }
        });

        Obligatorios3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Obligatorios3.setForeground(new java.awt.Color(204, 0, 51));
        Obligatorios3.setText("*");
        Obligatorios3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Obligatorios3MouseMoved(evt);
            }
        });

        Obligatorios7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Obligatorios7.setForeground(new java.awt.Color(204, 0, 51));
        Obligatorios7.setText("*");
        Obligatorios7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Obligatorios7MouseMoved(evt);
            }
        });

        Recontraseña.setBorder(null);
        Recontraseña.setEnabled(false);
        Recontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RecontraseñaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RecontraseñaKeyTyped(evt);
            }
        });

        PDseguridad.setBorder(null);
        PDseguridad.setEnabled(false);
        PDseguridad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PDseguridadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PDseguridadKeyTyped(evt);
            }
        });

        CodExiste.setEditable(false);
        CodExiste.setBackground(new java.awt.Color(255, 255, 255));
        CodExiste.setForeground(new java.awt.Color(51, 51, 51));
        CodExiste.setBorder(null);
        CodExiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodExisteActionPerformed(evt);
            }
        });

        usu.setEditable(false);
        usu.setBackground(new java.awt.Color(255, 255, 255));
        usu.setForeground(new java.awt.Color(51, 51, 51));
        usu.setBorder(null);

        Cexiste.setEditable(false);
        Cexiste.setBackground(new java.awt.Color(255, 255, 255));
        Cexiste.setBorder(null);
        Cexiste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CexisteActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_identification_documents_24px.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_user_32px.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_key_2_32px.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_security_lock_32px.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_security_lock_32px.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_microsoft_admin_30px.png"))); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(22, 44, 81));

        jSeparator3.setBackground(new java.awt.Color(22, 44, 81));

        jSeparator4.setBackground(new java.awt.Color(22, 44, 81));

        jSeparator5.setBackground(new java.awt.Color(22, 44, 81));

        jSeparator6.setBackground(new java.awt.Color(22, 44, 81));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Obligatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Ciusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(jSeparator2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Cexiste, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(CodExiste)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Reusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(jSeparator6))
                                .addGap(12, 12, 12)
                                .addComponent(usu, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Obligatorios1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addComponent(Recontraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Respuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Obligatorios7))
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Obligatorios2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(PDseguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(24, 24, 24)
                                            .addComponent(Obligatorios3))
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(GuardarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel8)
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Ciusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Cexiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(CodExiste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(137, 137, 137)
                            .addComponent(Obligatorios))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Obligatorios1)
                            .addComponent(Reusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Recontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Obligatorios2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PDseguridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Obligatorios3)))
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Respuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Obligatorios7)))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13))
                        .addGap(42, 42, 42)
                        .addComponent(GuardarUsuario)
                        .addGap(103, 103, 103))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(437, 437, 437))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(630, 50, 450, 600);

        BuscarUsu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BuscarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_property_26px.png"))); // NOI18N
        BuscarUsu.setText("Modificar");
        BuscarUsu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BuscarUsu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                BuscarUsuMouseMoved(evt);
            }
        });
        BuscarUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BuscarUsuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuscarUsuMouseExited(evt);
            }
        });
        BuscarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarUsuActionPerformed(evt);
            }
        });
        getContentPane().add(BuscarUsu);
        BuscarUsu.setBounds(240, 500, 120, 60);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGOR.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(710, 240, 650, 520);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/er.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 1230, 680);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarUsuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarUsuMouseEntered
        
    }//GEN-LAST:event_ActualizarUsuMouseEntered

    private void ActualizarUsuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarUsuMouseExited
         
    }//GEN-LAST:event_ActualizarUsuMouseExited

    private void ActualizarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarUsuActionPerformed
        CargarDatosUsuario();
    }//GEN-LAST:event_ActualizarUsuActionPerformed

    private void CiusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CiusuarioActionPerformed

    private void CiusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CiusuarioKeyReleased
        
        Validacion();
        Validacion2();
    }//GEN-LAST:event_CiusuarioKeyReleased

    private void CiusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CiusuarioKeyTyped
        char car = evt.getKeyChar();
        if (Ciusuario.getText().length() >= 8) {
            evt.consume();
        }
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_CiusuarioKeyTyped

    private void ReusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReusuarioActionPerformed

    private void ReusuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReusuarioKeyReleased
   
        ValidacionUsuario();
    }//GEN-LAST:event_ReusuarioKeyReleased

    private void ReusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReusuarioKeyTyped
        char b = evt.getKeyChar();
        if (Reusuario.getText().length() >= 10) {
            evt.consume();
        }
        if ((b < 'a' || b > 'z') && (b < '0' || b > '9') && (b < 'A' || b > 'Z')&& (b != 'ñ') && (b != 'Ñ')) {
            evt.consume();
        }
    }//GEN-LAST:event_ReusuarioKeyTyped

    private void RespuestasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RespuestasKeyReleased
R();        
    }//GEN-LAST:event_RespuestasKeyReleased

    private void RespuestasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RespuestasKeyTyped
        Character s = evt.getKeyChar();
        char b = evt.getKeyChar();
        if (Respuestas.getText().length() >= 15) {
            evt.consume();
        }
        if ((b < 'a' || b > 'z') && (b < '0' || b > '9') && (b < 'A' || b > 'Z') && (s != 'ñ') && (s != 'Ñ')&& (s != KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_RespuestasKeyTyped

    private void GuardarUsuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarUsuarioMouseMoved

    }//GEN-LAST:event_GuardarUsuarioMouseMoved

    private void GuardarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarUsuarioMouseEntered
       
    }//GEN-LAST:event_GuardarUsuarioMouseEntered

    private void GuardarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarUsuarioMouseExited
      
    }//GEN-LAST:event_GuardarUsuarioMouseExited

    private void GuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarUsuarioActionPerformed
        if (Ciusuario.getText().isEmpty() || Reusuario.getText().isEmpty() || Recontraseña.getText().isEmpty() || Respuestas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "rellene todos los campos obligatorios", "informacion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                String Cius, Usu, Con, Psegu, Rsegu, Carg;
                BDConexion.EntradaUsuario(
                    Usu = Reusuario.getText(),
                    Con = Recontraseña.getText(),
                    Carg = Cargo.getSelectedItem().toString(),
                    Psegu = PDseguridad.getText(),
                    Rsegu = Respuestas.getText(),
                    Cius = Ciusuario.getText());
                PDseguridad.setText("");
                Respuestas.setText("");
                Reusuario.setText("");
                Recontraseña.setText("");
                JOptionPane.showMessageDialog(null, "Guardado Exitoso");
          Respuestas.setEnabled(false);
             Reusuario.setEnabled(false);
          Recontraseña.setEnabled(false);
            PDseguridad.setEnabled(false);
            Cargo.setEnabled(false);   
            GuardarUsuario.setEnabled(false);   
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

        }
    }//GEN-LAST:event_GuardarUsuarioActionPerformed

    private void ObligatoriosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ObligatoriosMouseMoved
        Obligatorios.setToolTipText("Campo Obligatorio");
    }//GEN-LAST:event_ObligatoriosMouseMoved

    private void Obligatorios1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Obligatorios1MouseMoved
        Obligatorios.setToolTipText("Campo Obligatorio");
    }//GEN-LAST:event_Obligatorios1MouseMoved

    private void Obligatorios2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Obligatorios2MouseMoved
        Obligatorios.setToolTipText("Campo Obligatorio");
    }//GEN-LAST:event_Obligatorios2MouseMoved

    private void Obligatorios3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Obligatorios3MouseMoved
        Obligatorios.setToolTipText("Campo Obligatorio");
    }//GEN-LAST:event_Obligatorios3MouseMoved

    private void Obligatorios7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Obligatorios7MouseMoved
        Obligatorios.setToolTipText("Campo Obligatorio");
    }//GEN-LAST:event_Obligatorios7MouseMoved

    private void RecontraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RecontraseñaKeyReleased
        
    }//GEN-LAST:event_RecontraseñaKeyReleased

    private void RecontraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RecontraseñaKeyTyped
        char b = evt.getKeyChar();
        if (Recontraseña.getText().length() >= 10) {
            evt.consume();
        }
        if ((b < 'a' || b > 'z')&& (b < 'A' || b > 'Z') && (b < '0' || b > '9')&& (b != 'ñ') && (b != 'Ñ')) {
            evt.consume();
        }
    }//GEN-LAST:event_RecontraseñaKeyTyped

    private void PDseguridadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PDseguridadKeyReleased

        Respu();
        
    }//GEN-LAST:event_PDseguridadKeyReleased

    private void PDseguridadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PDseguridadKeyTyped
        SoloLetras.letrasYespacio(evt, PDseguridad.getText());
    }//GEN-LAST:event_PDseguridadKeyTyped

    private void BuscarUsuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarUsuMouseMoved

    }//GEN-LAST:event_BuscarUsuMouseMoved

    private void BuscarUsuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarUsuMouseEntered
          
    }//GEN-LAST:event_BuscarUsuMouseEntered

    private void BuscarUsuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuscarUsuMouseExited
       
    }//GEN-LAST:event_BuscarUsuMouseExited

    private void BuscarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarUsuActionPerformed
  Frame f=JOptionPane.getFrameForComponent(this);
        new ModificarUsuario(f,true).setVisible(true);    
    }//GEN-LAST:event_BuscarUsuActionPerformed

    private void RespuestasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespuestasActionPerformed

    }//GEN-LAST:event_RespuestasActionPerformed

    private void CodExisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodExisteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodExisteActionPerformed

    private void CargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargoActionPerformed

    private void CexisteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CexisteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CexisteActionPerformed
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(empleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton ActualizarUsu;
    public static javax.swing.JButton BuscarUsu;
    public static javax.swing.JComboBox<String> Cargo;
    private javax.swing.JTextField Cexiste;
    public static javax.swing.JTextField Ciusuario;
    private javax.swing.JTextField CodExiste;
    public static javax.swing.JButton GuardarUsuario;
    private javax.swing.JLabel Obligatorios;
    private javax.swing.JLabel Obligatorios1;
    private javax.swing.JLabel Obligatorios2;
    private javax.swing.JLabel Obligatorios3;
    private javax.swing.JLabel Obligatorios7;
    public static javax.swing.JTextField PDseguridad;
    public static javax.swing.JPasswordField Recontraseña;
    public static javax.swing.JTextField Respuestas;
    public static javax.swing.JTextField Reusuario;
    private javax.swing.JLabel Usuarios;
    public static javax.swing.JTable UsuariosRegistrados;
    private javax.swing.JPanel inferior;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel pinferior;
    private javax.swing.JTextField usu;
    // End of variables declaration//GEN-END:variables
}
