/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reporte;

import Conexiones.BDConexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author rosan
 */
public class SeccionesDisponibles extends javax.swing.JDialog {

    /**
     * Creates new form SeccionesDisponibles
     */
    public SeccionesDisponibles(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
           setSize(786, 448);
           this.setLocationRelativeTo(null);
    }
  public void Validacion() {
     String mensaje=BDConexion.bucarCi(id.getText());
     if(mensaje.equals("El Codigo Existe")){
         CodExiste.setText("Codigo Registrado"); 
            buscar.setEnabled(true);
         
     }else if(id.getText().isEmpty()){
     CodExiste.setText("");
         
     }else{
        CodExiste.setText("Codigo no Registrado"); 
      buscar.setEnabled(false);
           
            }
            
     
}
       public void Reporte5() throws SQLException,JRException {
        Connection conn;
     
      int x=Integer.parseInt(id.getText());
       
    
      conn=DriverManager.getConnection("jdbc:sqlserver://localhost:49162;databaseName=PCEPC","sa","12");
      JasperReport report = JasperCompileManager.compileReport("C:\\Proyecto\\build\\classes\\Reporte\\SeccionesDispo.jrxml");
      Map parametro = new HashMap();
      parametro.put("ID" ,x);
   
      
      
      JasperPrint print = JasperFillManager.fillReport(report, parametro, conn);  
      
      
     
      JasperViewer jw = new JasperViewer(print,false);
      jw.setTitle("Reporte Disponibilidad Secciones");
      jw.setVisible(true);
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Volver1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        CodExiste = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Listado de Status ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(413, 80, 179, 50);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGOR.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(-260, 60, 590, 540);

        Volver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_go_back_60px.png"))); // NOI18N
        Volver1.setBorder(null);
        Volver1.setContentAreaFilled(false);
        Volver1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                Volver1MouseMoved(evt);
            }
        });
        Volver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volver1ActionPerformed(evt);
            }
        });
        jPanel2.add(Volver1);
        Volver1.setBounds(240, 10, 80, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 330, 490);

        jSeparator3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(373, 246, 110, 10);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Código Curso:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(380, 190, 100, 20);

        id.setBorder(null);
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        jPanel1.add(id);
        id.setBounds(380, 220, 100, 20);

        buscar.setForeground(new java.awt.Color(204, 204, 204));
        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/j.png"))); // NOI18N
        buscar.setBorder(null);
        buscar.setContentAreaFilled(false);
        buscar.setEnabled(false);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar);
        buscar.setBounds(430, 310, 110, 60);

        CodExiste.setEditable(false);
        CodExiste.setBackground(new java.awt.Color(255, 255, 255));
        CodExiste.setForeground(new java.awt.Color(51, 51, 51));
        CodExiste.setBorder(null);
        jPanel1.add(CodExiste);
        CodExiste.setBounds(490, 220, 130, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 0, 630, 450);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pexels-photo-5212338.jpeg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 980, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
        Validacion();
    }//GEN-LAST:event_idKeyReleased

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        char car = evt.getKeyChar();
        char b = evt.getKeyChar();
        if(id.getText().length()>=4) evt.consume();
        if((car<'0' || car>'9')&&(b<'a' || b >'z') && (b<'A' || b >'Z')) evt.consume();
    }//GEN-LAST:event_idKeyTyped

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try {
            Reporte5();
        } catch (SQLException ex) {
            Logger.getLogger(SeccionesDisponibles.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(SeccionesDisponibles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void Volver1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Volver1MouseMoved
        Volver1.setToolTipText("Volver");
    }//GEN-LAST:event_Volver1MouseMoved

    private void Volver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volver1ActionPerformed
        dispose();
    }//GEN-LAST:event_Volver1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeccionesDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeccionesDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeccionesDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeccionesDisponibles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SeccionesDisponibles dialog = new SeccionesDisponibles(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodExiste;
    private javax.swing.JButton Volver1;
    private javax.swing.JButton buscar;
    public javax.swing.JTextField id;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
