/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Reporte;

import Conexiones.BDConexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author rosan
 */
public class Secciones extends javax.swing.JDialog {

    /**
     * Creates new form EstudianteRepor
     */
    public Secciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
      initComponents();
      setSize(786, 448);
           this.setLocationRelativeTo(null);
    }
      public void Reporte2() throws SQLException,JRException {
        Connection conn;
     
      int x=Integer.parseInt(NombreS.getText());
      conn=DriverManager.getConnection("jdbc:sqlserver://localhost:49162;databaseName=PCEPC","sa","12");
      JasperReport report = JasperCompileManager.compileReport("C:\\Proyecto\\build\\classes\\Reporte\\Secciones.jrxml");
      Map parametro = new HashMap();
      parametro.put("NOMBRE" ,x);
      
      
      JasperPrint print = JasperFillManager.fillReport(report, parametro, conn);  
      
      
     
      JasperViewer jw = new JasperViewer(print,false);
      jw.setTitle("");
      jw.setVisible(true);
      
    }
   public void ValidacionSeccion() {
     String mensaje=BDConexion.ChequearSeccion(NombreS.getText());
     if(mensaje.equals("Seccion disponible")){
         CodSeccionn.setText("Sección disponible");   
          buscar.setEnabled(true);
     }else if(NombreS.getText().isEmpty()){
     CodSeccionn.setText("");
        
     }else{
        CodSeccionn.setText("Seccion Finalizada o no Existe"); 
                 buscar.setEnabled(false);
             }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Volver = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        NombreS = new javax.swing.JTextField();
        CodSeccionn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Listado Estudiantil ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(413, 80, 179, 50);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGOR.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(-260, 60, 590, 540);

        Volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_go_back_60px.png"))); // NOI18N
        Volver.setBorder(null);
        Volver.setContentAreaFilled(false);
        Volver.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                VolverMouseMoved(evt);
            }
        });
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel2.add(Volver);
        Volver.setBounds(220, 10, 90, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 330, 490);

        jSeparator3.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(370, 240, 100, 10);

        buscar.setForeground(new java.awt.Color(204, 204, 204));
        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/j.png"))); // NOI18N
        buscar.setBorder(null);
        buscar.setContentAreaFilled(false);
        buscar.setEnabled(false);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar);
        buscar.setBounds(420, 300, 110, 60);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nombre de la Sección:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(370, 180, 130, 20);

        NombreS.setBorder(null);
        NombreS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NombreSKeyReleased(evt);
            }
        });
        jPanel1.add(NombreS);
        NombreS.setBounds(370, 220, 100, 20);

        CodSeccionn.setEditable(false);
        CodSeccionn.setBackground(new java.awt.Color(255, 255, 255));
        CodSeccionn.setForeground(new java.awt.Color(51, 51, 51));
        CodSeccionn.setBorder(null);
        CodSeccionn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodSeccionnActionPerformed(evt);
            }
        });
        jPanel1.add(CodSeccionn);
        CodSeccionn.setBounds(490, 220, 120, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 0, 630, 450);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pexels-photo-5212338.jpeg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 980, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreSKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreSKeyReleased
        ValidacionSeccion();
    }//GEN-LAST:event_NombreSKeyReleased

    private void VolverMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseMoved
        Volver.setToolTipText("Volver");
    }//GEN-LAST:event_VolverMouseMoved

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        dispose();
    }//GEN-LAST:event_VolverActionPerformed

    private void CodSeccionnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodSeccionnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodSeccionnActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        try {
            Reporte2();
        } catch (SQLException ex) {
            Logger.getLogger(Secciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(Secciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Secciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Secciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Secciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Secciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Secciones dialog = new Secciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodSeccionn;
    public javax.swing.JTextField NombreS;
    private javax.swing.JButton Volver;
    private javax.swing.JButton buscar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
